Second iteration
MrDenli/go-db-sql pull request #2
Opened 2024-08-08 15:22 UTC by MrDenli

2024-08-08 16:48 UTC, dirtymew requested changes
Привет Данил

есть еще что поправить

2024-08-08 16:48 UTC, dirtymew commented on main.go
> +	db, err := sql.Open("sqlite", "tracker.db")
все ревью должно быть в одном PR

так история сохраниться в одном месте

2024-08-08 16:48 UTC, dirtymew commented on parcel.go
> +		return err
тут нужно свою ошибку вернуть а ты вернешь nil

и нужно тогда main функцию поправить там тесты они до конца не дойдут

2024-08-08 16:48 UTC, dirtymew commented on parcel.go
> +	if rowsAffected == 0 {
тут нужно свою ошибку вернуть а ты вернешь nil

и нужно тогда main функцию поправить там тесты они до конца не дойдут

2024-08-08 16:48 UTC, dirtymew commented on parcel_test.go
> +	assert.Error(t, err)
require.Error

и хорошо бы проверить саму ошибку - assert.Erroris

2024-08-08 16:48 UTC, dirtymew commented on parcel_test.go
> +		require.Equal(t, expected, p)
assert

2024-08-09 01:02 UTC, MrDenli commented
third commit

2024-08-09 01:02 UTC, merged